######################################################################
# Automatically generated by qmake (1.06c) ?? 11. ??? 08:09:18 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += ./src
CONFIG += console

# Input
HEADERS +=
SOURCES += ./src/ConsoleApplication/main.cpp
