######################################################################
# Automatically generated by qmake (1.06c) ?? 11. ??? 08:09:18 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += ./src

# Input
HEADERS += ./src/saper.h \
	 src/cell.h \
	 src/saperbutton.h \
	 src/saperboard.h
SOURCES += ./src/main.cpp ./src/saper.cpp \
	 src/cell.cpp \
	 src/saperbutton.cpp \
	 src/saperboard.cpp
