######################################################################
# Automatically generated by qmake (1.06c) ?? 11. ??? 08:09:18 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += ./src

# Input
HEADERS += src/TerminalApplication/STerminalApplication.h
SOURCES += ./src/TerminalApplication/main.cpp \
	src/TerminalApplication/STerminalApplication.cpp
